import { RaceKey } from './race-key';
import { RaceLabel } from './race-label';

export const raceMap = new Map<RaceKey, RaceLabel>([
  ['Herald', '大天使'],
  ['Megami', '女神'],
  ['Avian', '霊鳥'],
  ['Deity', '魔神'],
  ['Avatar', '神獣'],
  ['Holy', '聖獣'],
  ['Genma', '幻魔'],
  ['Fury', '破壊神'],
  ['Dragon', '龍神'],
  ['Lady', '地母神'],
  ['Kishin', '鬼神'],
  ['Divine', '天使'],
  ['Yoma', '妖魔'],
  ['Snake', '龍王'],
  ['Beast', '魔獣'],
  ['Fairy', '妖精'],
  ['Jirae', '地霊'],
  ['Jaki', '邪鬼'],
  ['Fallen', '堕天使'],
  ['Brute', '妖鬼'],
  ['Femme', '鬼女'],
  ['Night', '夜魔'],
  ['Vile', '邪神'],
  ['Raptor', '凶鳥'],
  ['Wood', '妖樹'],
  ['Wilder', '妖獣'],
  ['Foul', '外道'],
  ['Tyrant', '魔王'],
  ['Drake', '邪龍'],
  ['Haunt', '幽鬼'],
  ['Enigma', '秘神'],
  ['Entity', '威霊'],
  ['Rumor', '怪異'],
  ['UMA', '珍獣'],
  ['Zealot', '狂神'],
]);
